# 
# TravisCI config - SKALE Manager
# Copyright (C) 2018-Present SKALE Labs
# @author Artem Payvin
#
# SKALE Manager is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SKALE Manager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with SKALE Manager.  If not, see <https://www.gnu.org/licenses/>.

language: node_js
node_js:
  - "10"
os: linux
dist: bionic
env:
  global:
    - NODE_OPTIONS="--max_old_space_size=4096"
addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
install:
    - yarn install
    - pip3 install slither-analyzer
before_script:
    - npx ganache-cli --gasLimit 8000000 --quiet --account="$PRIVATE_KEY_1, 1000000000000000000000000" --account="$PRIVATE_KEY_2, 1000000000000000000000000" --account="$PRIVATE_KEY_3, 1000000000000000000000000" --account="$PRIVATE_KEY_4, 1000000000000000000000000" --account="$PRIVATE_KEY_5, 1000000000000000000000000" &
    - npx testrpc-sc --port 8555 --gasLimit 0xfffffffffff --quiet --account="$PRIVATE_KEY_1, 1000000000000000000000000" --account="$PRIVATE_KEY_2, 1000000000000000000000000" --account="$PRIVATE_KEY_3, 1000000000000000000000000" --account="$PRIVATE_KEY_4, 1000000000000000000000000" --account="$PRIVATE_KEY_5, 1000000000000000000000000" &
script:
    - yarn lint || travis_terminate 1
    - slither --version
    - slither . || true
    - slither . --exclude reentrancy-events,reentrancy-benign,naming-convention,solc-version,assembly,timestamp,calls-loop,reentrancy-no-eth,constant-function,pragma --filter-path @openzeppelin/contracts/ || travis_terminate 5
    - yarn tslint || travis_terminate 2
    - yarn generate    
    - yarn test || travis_terminate 3
    - VERSION=$(BRANCH=$TRAVIS_BRANCH bash ./scripts/calculate_version.sh)
    - echo "Version $VERSION"
    - export VERSION=$VERSION
    - export BRANCH=$TRAVIS_BRANCH
after_script:
    - npx solidity-coverage || travis_terminate 4
    - cat coverage/lcov.info | npx codecov
before_deploy:
  # Set up git user name and tag this commit
  - (
    test ! $TRAVIS_TAG &&
    git config --local user.name "skale-travis" &&
    git config --local user.email "$GITHUB_EMAIL" &&
    export TRAVIS_TAG=$VERSION &&
    git tag "$TRAVIS_TAG" &&
    git push https://$GITHUB_OAUTH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_TAG
    ) || true
deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    skip_cleanup: true
    name: $VERSION @ $(date +'%d.%m.%Y %R')
    on:
      repo: $TRAVIS_REPO_SLUG
      branch: master
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    skip_cleanup: true
    prerelease: true
    name: $VERSION @ $(date +'%d.%m.%Y %R')
    on:
      repo: $TRAVIS_REPO_SLUG
      branch:
        - develop
        - beta
        - stable
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/scripts/build_and_publish.sh
    on:
      repo: $TRAVIS_REPO_SLUG
      branch:
        - master
        - stable
        - develop
        - beta